[package]
name = "trgt"
version = "1.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
vergen = { version = "8.2", features = ["git", "gitcl"] }

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rust-htslib = { version = "0.46", default-features = false }
itertools = "0.12"
bio = "1.6"
env_logger = "0.10"
log = "0.4"
chrono = "0.4"
arrayvec = "0.7"
kodama = "0.3"
rand = "0.8"
once_cell = "1.18"
flate2 = "1.0"
resvg = "0.36"
usvg = "0.36"
tiny-skia = "0.11"
svg2pdf = "0.9"
tempfile = "3"
rayon = "1.10"
crossbeam-channel = "0.5"
semver = "1.0"