[package]
name = "pipeplot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.36"
usvg = "0.36"
tiny-skia = "0.11"
svg2pdf = "0.9"
tempfile = "3"
